### ISSUE TITLE
Response headers produces invalid result

### ISSUE THREAD

**Issue by drjonnicholson** [zhandao/zero-rails_openapi#48]
The addition of headers in responses (#42)  is great, but it appears to produce properties that are not compliant with the OpenAPI specification.

Example output:

```YAML
          headers:
            page:
              description: The current page
              schema:
                minimum: 1
                default: 1
                example: 2
                _enum: null
                _length: null
                _pattern: null
                _desc: null
```

The properties `_enum`, `_length`, `_pattern`, and `_desc` are invalid, and I believe they all come from https://github.com/zhandao/zero-rails_openapi/blob/master/lib/oas_objs/schema_obj.rb#L113, but I may be wrong. I've not yet traced back why these are bleeding through to the output though.

Small example of generating code:

```Ruby
headers = {
  page:  { desc: I18n.t('api.headers.page'), type: Integer, minimum: 1, default: 1, example: 2 }
}
response(200, 'Success', type, headers: headers, data: data)
```
